name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker Layer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/cache@master
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 12
      uses: actions/setup-java@master
      with:
        java-version: 12
    - name: Build and test project
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export MVN_PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "::set-env name=MVN_PROJECT_VERSION::$MVN_PROJECT_VERSION"
        mvn -DskipTests=true --no-transfer-progress clean package
        
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag rtdi/connectorrootapp:latest
    - name: Login to DockerHub Registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Push the latest Docker image
      run: docker push rtdi/connectorrootapp:latest
      
